services:
  ha-time-machine:
    image: ghcr.io/diggingfordinos/homeassistanttimemachine:latest
    container_name: ha-time-machine
    ports:
      - "54000:54000"
    environment:
      - HOME_ASSISTANT_URL=http://192.168.1.4:8123
      - LONG_LIVED_ACCESS_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkYjk4MDExZjVjODE0NjVkYTc1ZDkxZmI5MTUzNjJjOSIsImlhdCI6MTYxNDg3ODY2NSwiZXhwIjoxOTMwMjM4NjY1fQ.xn2YubpSpne-lrTOWyrisA5vcTBNfaVJLTTN_xnYujc
    volumes:
      - /mnt/homeassistant/config:/config
      - /mnt/homeassistant/timemachine:/media/timemachine
      - ha-time-machine-data:/data
    restart: unless-stopped
volumes:
  ha-time-machine-data:
