backup_now:
  description: Triggers an immediate backup in Home Assistant Time Machine.
  fields:
    url:
      description: The URL of your Time Machine instance (e.g., http://451bbd22-homeassistant-time-machine:54000).
      example: "http://451bbd22-homeassistant-time-machine:54000"
